<h3>Introduction to Classification</h3>

<h3>The Iris Dataset</h3>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

#Creating Dataframe
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
df['species'] = df['target'].apply(lambda x: iris.target_names[x])


df.head(125)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,species
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa
...,...,...,...,...,...,...
120,6.9,3.2,5.7,2.3,2,virginica
121,5.6,2.8,4.9,2.0,2,virginica
122,7.7,2.8,6.7,2.0,2,virginica
123,6.3,2.7,4.9,1.8,2,virginica
124,6.7,3.3,5.7,2.1,2,virginica